### ISSUE TITLE
Unable to start server using instructions provided

### ISSUE THREAD

**Issue by epequeno-fr** [jaredjensen/go-swagger-starter#1]
Starting from these instructions (from the README)

```
1. Copy this starter into the monorepo
2. Define the API spec in the /swagger folder
3. Run make generate to generate docs and server
4. Implement your endpoint handlers
5. Run a local server with make run_local to test
```

I copied this repo into a folder, made **NO** changes to the `*.yaml` files in `./swagger`, then tried to run `make generate` and got the following error:

```
$ make generate
Installing swagger-merger
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "swagger-merger@1.4.3" with binaries:
      - swagger-merger
✨  Done in 1.90s.
Merging swagger specification files
Running validate_swagger
make: swagger: No such file or directory
make: *** [validate_swagger] Error 1
```

`validate_swagger` expected the `docs_gen` folder to exist but it doesn't seem like that was really a problem, just noting that maybe the repo should include that empty dir so the makefile doesn't error on this step.

But running the next step is where I'm getting an error I'm not sure how to handle

```
$ make run_local
Error from server (Forbidden): secrets "rsfilter-resource-server" is forbidden: User "estevan.pequeno@forgerock.io" cannot get resource "secrets" in API group "" in the namespace "fr-platform": requires one of ["container.secrets.get"] permission(s).
stat ./swagger_gen/cmd/main.go: no such file or directory
make: *** [run_local] Error 1
```

**Comment by jaredjensen** [comment]
Discussed in Slack, but the gist is:

- `go-swagger` needs to be installed
- The kube context needs to be set for AM authentication

I updated the README with these details.
